spring.application.name=2_Zomato


# Spring datasource properties
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/Zomato
spring.datasource.username=root
spring.datasource.password=Pradip@2001

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


